language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_db2de606fa4d_key -iv $encrypted_db2de606fa4d_iv
  -in named-equator-246401-c8a53df5c9c1.json.enc -out named-equator-246401-c8a53df5c9c1.json
  -d
deploy:
  provider: gae
  keyfile: named-equator-246401-c8a53df5c9c1.json
  project: named-equator-246401
