export const SET_FILTER_RANGE = "SET_FILTER_RANGE";
export const APPLY_FILTER_RANGE = "APPLY_FILTER_RANGE";

export const SET_FILTER_RANGE_CB = "SET_FILTER_RANGE_CB";
export const APPLY_FILTER_RANGE_CB = "APPLY_FILTER_RANGE_CB";
